config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"
  # Define your application routes per theww DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # get 'bookings/create'
  # get 'bookings/destroy'

  # get "admin", to: "admin#index"
  # delete "admin", to: "admin#destroy"

  resources :admin, only: [:index]

  resources :fitness_equipments do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings do
    member do
      patch 'accept'
      patch 'reject'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :fitness_equipment
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :fitness_equipments
end

app/models/fitness_equipment.rb
class FitnessEquipment < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo

  include PgSearch::Model
  pg_search_scope :search_by_title_and_description,
    against: [ :name, :description ],
    associated_against: {
      user: [ :first_name, :last_name ]
    },
    using: {
      tsearch: { prefix: true }
    }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings
  has_many :fitness_equipments, through: :bookings

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  def index
    @mylistings = FitnessEquipment.where(user_id: current_user.id)

    @booked_equipments = get_bookings_made

    @top_booked = get_top_booked_equipments
  end

  private

  def get_bookings_made
    Booking.all.where.not(user_id: current_user.id)
    # .where(status: "Pending")
  end

  def get_top_booked_equipments
    FitnessEquipment.joins(:bookings)
                          .group('fitness_equipments.id')
                          .order('COUNT(bookings.id) DESC')
                          .limit(3)
                          .select('fitness_equipments.*, COUNT(bookings.id) AS booking_count')
                          .where(user_id: current_user.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address, :district, :admin])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :address, :district, :admin])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  before_action :set_fitness_equipment, only: [:new, :create]
  before_action :set_booking, only: %i[show edit update destroy reject accept]

  def index
    @bookings = Booking.all.order(date_from: :desc).where('user_id = ? AND date_to >= ?', current_user.id, Date.today)

    @previous_bookings = Booking.all.order(date_from: :desc).where('user_id = ? AND date_to < ?', current_user.id, Date.today)
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.status = "Pending"
    @booking.fitness_equipment = @fitness_equipment
    @booking.user = current_user

    days_diff = (@booking.date_to - @booking.date_from).to_i
    @booking.total = days_diff * @fitness_equipment.price

    @booking_exists = Booking.where(fitness_equipment_id: @fitness_equipment.id).where('date_from >= ? AND date_to<= ?',@booking.date_from, @booking.date_to).count

    # if @booking.save
    #   redirect_to bookings_path
    # end

    if @booking_exists > 0
      @booking.errors.add(:base, "There is already a booking for this date range")
      # render :new, status: :unprocessable_entity
    elsif @booking.save
      redirect_to bookings_path
    else
      @booking = Booking.new
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @booking.destroy
    redirect_to bookings_path, status: :see_other
  end

  def edit
  end

  def update
    @booking.update(booking_params)
    days_diff = (@booking.date_to - @booking.date_from).to_i
    @fitness_equipment_booking = FitnessEquipment.find(@booking.fitness_equipment_id)
    @booking.total = days_diff * @fitness_equipment_booking.price
    @booking.save

    redirect_to bookings_path
  end

  def accept
    @booking.update(status: 'Accepted')
    redirect_to admin_index_path, notice: 'Booking accepted successfully.'
  end

  def reject
    @booking.update(status: 'Rejected')
    redirect_to admin_index_path, notice: 'Booking rejected.'
  end


  private

  def set_fitness_equipment
    @fitness_equipment = FitnessEquipment.find(params[:fitness_equipment_id])
  end

  def booking_params
    params.require(:booking).permit(:date_from, :date_to, :fitness_equipment_id, :status, :total)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end
end

app/controllers/fitness_equipments_controller.rb
class FitnessEquipmentsController < ApplicationController

  before_action :set_equipment, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @categories = Category.all
    @category_selected = 0
    if params[:category].present?
      @category_selected = params[:category].to_i
      if user_signed_in?
        @equipments = FitnessEquipment.where(category_id: @category_selected).where.not(user_id: current_user.id)
      else
        @equipments = FitnessEquipment.where(category_id: @category_selected)
      end
    elsif params[:query].present?
      if user_signed_in?
        @equipments = FitnessEquipment.search_by_title_and_description(params[:query]).where.not(user_id: current_user.id)
      else
        @equipments = FitnessEquipment.search_by_title_and_description(params[:query])
      end
    else
      #else display all
      # @equipments = FitnessEquipment.all
      if user_signed_in?
        @equipments = FitnessEquipment.where.not(user_id: current_user.id)
      else
        @equipments = FitnessEquipment.all
      end
    end
  end

  def show
    @category = Category.find(@equipment.category_id)
    @owner = User.find(@equipment.user_id)
    @booking = Booking.new(fitness_equipment: @equipment)

    @marker = {
                  lat: @owner.latitude,
                  lng: @owner.longitude,
                  info_window_html: render_to_string(partial: "info_window", locals: {user: @owner}),
                  marker_html: render_to_string(partial: "marker", locals: {user: @owner})
              }
  end

  def edit
  end

  def update
    @equipment.update(equipment_params)
    redirect_to fitness_equipment_path(@equipment), notice: 'Equipment was successfully updated.'
  end

  def destroy
    @equipment.destroy!
    redirect_to admin_index_path, status: :see_other
  end

  def new
    @equipment = FitnessEquipment.new
  end

  def create
    @equipment = FitnessEquipment.new(equipment_params)
    @equipment.user_id = current_user.id
    @equipment.available = true

    @equipment.save
    if @equipment.save
      redirect_to admin_index_path
      # redirect_to fitness_equipment_path(@equipment)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def filter
    puts "filterrr"
  end

  private

  def set_equipment
    @equipment = FitnessEquipment.find(params[:id])
  end

  def equipment_params
    params.require(:fitness_equipment).permit(:name, :category_id, :description, :price, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home

    today = Date.today
    beginning_month = today.beginning_of_month
    end_month = today.end_of_month

    @top_equipments = FitnessEquipment.joins(:bookings)
                          .group('fitness_equipments.id')
                          .order('COUNT(bookings.id) DESC')
                          .limit(3)
                          .select('fitness_equipments.*, COUNT(bookings.id) AS booking_count')
                          .where('bookings.date_from >= ? and bookings.date_to <=?', beginning_month, end_month)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/index.html.erb
<div class="p-5 mx-auto" style="width: 90vw" >
  <h2>Got any new equipment, you want to rent out ?
    <%= link_to "Add here", new_fitness_equipment_path, class:"text-decoration-none" %>
  </h2>
</div>

<div data-controller= "hide-show-div">
  <div class="buttons" >
  <button type="button" class="btn btn-secondary" data-action="click->hide-show-div#show_current" data-hide-show-div-target="currentbtn">My equipments</button>
  <button type="button" class="btn btn-outline-secondary" data-action="click->hide-show-div#show_previous" data-hide-show-div-target="previousbtn">Booked equipments</button>
  </div>

  <div data-hide-show-div-target="current">
    <div class="p-5 mx-auto" style="width: 90vw" >
      <h1>My equipments for rent</h1>
      <table class="table table-striped" id="booking-table">
        <thead>
          <tr>
            <th scope="col">Equipment</th>
            <th scope="col">Category</th>
            <th scope="col">Made available on</th>
            <th scope="col">Price/day</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @mylistings.each do |equipment| %>
          <tr>
            <td>
              <%= cl_image_tag equipment.photo.key, height: 40, width: 40, crop: :fill, radius: 50 if equipment.photo.attached? %>
              <%= equipment.name %>
            </td>
            <td>
              <%=  image_tag(Category.find(equipment.category_id).image, style: "width: 30px;") %>
              <%= Category.find(equipment.category_id).name %>
            </td>
            <td><%= equipment.created_at.strftime("%d %b %Y") %></td>
            <td><%= equipment.price %> </td>
            <td>
                <%= link_to image_tag("edit.png", style: "width: 20px;"), edit_fitness_equipment_path(equipment.id), class: "actions-icon" %>
                <%#= link_to image_tag("edit", height: 25, width: 25), edit_fitness_equipment_path(equipment.id), class: "actions-icon" %>
                <%= link_to image_tag("delete.png", style: "width: 20px;"), fitness_equipment_path(equipment.id), class: "actions-icon", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}  %>
            </td>
        <% end %>
        </tbody>
      </table>

      <div class="most-booked" style="margin-top:40px">
        <h1>Top 3 Most booked</h1>
          <% @top_booked.each_with_index do |equipment, index| %>
            <ul class="list-group">
              <li class="list-group-item d-flex justify-content-between align-items-center">
                <%= equipment.name %>
                <% num_booked_class = "num-booked num-booked-#{index+1}" %>
                <button class="<%= num_booked_class %>"> <%= equipment.booking_count %></button>
              </li>
            </ul>
          <% end %>
      </div>

  </div>


  </div>

  <div data-hide-show-div-target="previous" class="d-none">
    <div class="p-5 mx-auto" style="width: 90vw" id="booking-table">
    <h1>Booked Equipments by other users</h1>
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">Equipment</th>
          <th scope="col">Requested by</th>
          <th scope="col">Date</th>
          <th scope="col">Total</th>
          <th scope="col">Status</th>
        </tr>
      </thead>
      <tbody>
        <% @booked_equipments.each do |booking| %>
          <% equipment = FitnessEquipment.find(booking.fitness_equipment_id) %>
          <% user = User.find(booking.user_id) %>
          <tr>
            <td>
              <%= cl_image_tag equipment.photo.key, height: 40, width: 40, crop: :fill, radius: 50 if equipment.photo.attached? %>
              <%= equipment.name %>
            </td>
            <td><%= "#{user.first_name} #{user.last_name} " %></td>
            <td><%= "#{booking.date_from.strftime("%d %b")} - #{booking.date_to.strftime("%d %b %Y")}"%></td>
            <td><%= booking.total %></td>
            <td>
              <% status_class = "status #{booking.status}" %>
              <span class= "<%= status_class %>">
                <%= booking.status %>
              </span>
            </td>

            <td>
            <% if booking.status == "Pending" %>
                <div class="booking-options">

                  <%= form_for booking, url: accept_booking_path(booking.id), method: :patch do |f| %>
                    <%= f.hidden_field :status, value: 'Accepted' %>
                    <%= f.submit 'Accept', class: 'options-accept' %>
                  <% end %>
                  <%= form_for booking, url: reject_booking_path(booking.id), method: :patch do |f| %>
                    <%= f.hidden_field :status, value: 'Rejected' %>
                    <%= f.submit 'Reject', class: 'options-reject' %>
                  <% end %>
                </div>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
    </div>
  </div>
</div>

app/views/bookings/edit.html.erb
<div class="p-5 mx-auto" style="width: 50vw; text-align: center" >
  <h2>Edit booking</h2>
</div>


<div class="container d-flex justify-content-center align-items-center" style="width: 100vw; height: 40%;">
  <div class="bg-dark p-4 rounded" style="width: 50vw; height: 40%;">
  <%= simple_form_for [@equipment, @booking],  data: { controller: 'flatpickr' } do |f| %>

    <%= f.association :fitness_equipment, as: :select %>

    <%= f.input :date_from, as: :string, input_html: { data: { flatpickr_target: "startDate" } } %>
    <%= f.input :date_to, as: :string, input_html: { data: { flatpickr_target: "endDate" } } %>


    <%= f.submit 'Edit booking', style: 'width: 100%; background-color:#9eeff5' %>
  <% end %>
  </div>
</div>

app/views/bookings/index.html.erb
<div data-controller= "hide-show-div">
  <div class="buttons" >
  <button type="button" class="btn btn-secondary" data-action="click->hide-show-div#show_current" data-hide-show-div-target="currentbtn">Current Bookings</button>
  <button type="button" class="btn btn-outline-secondary" data-action="click->hide-show-div#show_previous" data-hide-show-div-target="previousbtn">Previous Bookings</button>
  </div>


  <div data-hide-show-div-target="current">
    <div class="p-5 mx-auto" style="width: 90vw"  >
      <h1>Current Bookings</h1>

      <table class="table table-striped" id="booking-table" >
        <thead>
          <tr>
            <th scope="col">Equipment</th>
            <th scope="col">Category </th>
            <th scope="col">Date</th>
            <th scope="col">Price/day</th>
            <th scope="col">Total</th>
            <th scope="col">Status</th>
          </tr>
        </thead>
        <tbody>
          <% @bookings.each do |booking| %>
          <tr>
            <% equipment = FitnessEquipment.find(booking.fitness_equipment_id)  %>
            <td>
              <%= cl_image_tag equipment.photo.key, height: 40, width: 40, crop: :fill, radius: 50 if equipment.photo.attached? %>
              <%= equipment.name %>
            </td>
            <td>
              <%=  image_tag(Category.find(equipment.category_id).image, style: "width: 30px;") %>
              <%= Category.find(equipment.category_id).name %>
            </td>
            <td><%= "#{booking.date_from.strftime("%d %b")} - #{booking.date_to.strftime("%d %b %Y")}" %> </td>
            <td><%= equipment.price %> </td>
            <td><%= booking.total %> </td>
            <td>
            <% status_class = "status #{booking.status}" %>
            <span class= "<%= status_class %>">
                <%= booking.status %>
              </span>
            <% if booking.status == "Pending"%>
              <td>
                <%= link_to image_tag("edit.png", style: "width: 20px;"), edit_booking_path(booking), class: "actions-icon" %>
                <%= link_to image_tag("delete.png", style: "width: 20px;"), booking_path(booking), class: "actions-icon", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}  %>
              </td>
            <% else %>
              <td></td>
            <% end %>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <div data-hide-show-div-target="previous" class="d-none">

    <div class="p-5 mx-auto" style="width: 90vw" >
      <h1>Previous Bookings</h1>
      <table class="table table-striped" id="booking-table"  >
        <thead>
          <tr>
            <th scope="col">Equipment</th>
            <th scope="col">Category </th>
            <th scope="col">Date</th>
            <th scope="col">Price/day</th>
            <th scope="col">Total</th>
            <th scope="col">Status</th>
          </tr>
        </thead>
        <tbody>
          <% @previous_bookings.each do |booking| %>
          <tr>
            <% equipment = FitnessEquipment.find(booking.fitness_equipment_id)  %>
            <td>
              <%= cl_image_tag equipment.photo.key, height: 40, width: 40, crop: :fill, radius: 50 if equipment.photo.attached? %>
              <%= equipment.name %>
            </td>
            <td>
              <%=  image_tag(Category.find(equipment.category_id).image, style: "width: 30px;") %>
              <%= Category.find(equipment.category_id).name %>
            </td>
            <td><%= "#{booking.date_from.strftime("%d %b")} - #{booking.date_to.strftime("%d %b %Y")}" %> </td>
            <td><%= equipment.price %> </td>
            <td><%= booking.total %> </td>
            <td>
            <% status_class = "status #{booking.status}" %>
            <span class= "<%= status_class %>">
                <%= booking.status %>
            </span>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
 </div>

app/views/bookings/new.html.erb
  <h1>There is already a booking for this date</h1>

  <h5>Book</h5>
    <%#= simple_form_for [@equipment, @booking], data: { controller: 'flatpickr' } do |f| %>

    <%= simple_form_for [@equipment, @booking] do |f| %>


      <%= f.submit class:"btn btn-flat" %>

    <% end %>

<div class="container d-flex justify-content-center align-items-center" style="width: 100vw; height: 50vh;">
  <div class="bg-dark p-4 rounded" style="width: 50vw; height: 50vh;">

  <%= simple_form_for [@equipment, @booking],  data: { controller: 'flatpickr' } do |f| %>

    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <%= f.association :fitness_equipment, as: :select %>
    <%= f.input :date_from, as: :string, input_html: { data: { flatpickr_target: "startDate" } } %>
    <%= f.input :date_to, as: :string, input_html: { data: { flatpickr_target: "endDate" } } %>


    <%= f.submit 'Confirm', style: 'width: 100%; background-color:#9eeff5' %>
  <% end %>

</div>

app/views/fitness_equipments/_info_window.html.erb
<%# <h2>= fitness_equipment.name</h2> %>

<p>📍 <%=user.address %></p>
<% count = FitnessEquipment.where(user_id: @equipment.user_id).count %>
<p><%= user.first_name %> <%= user.last_name %> has
  <strong> <%= link_to count, fitness_equipments_path(query: "#{user.first_name} #{user.last_name}" ) %></strong>
  equipments
</p>

app/views/fitness_equipments/_marker.html.erb
<div class="marker">
<%= image_tag "pin.png", height: 50, width: 50, alt: "markerlogo" %>
<div class="badge rounded-pill bg-info text-dark fs-6">
  <%= "#{user.first_name} #{user.last_name}"%>
</div>
</div>

app/views/fitness_equipments/index.html.erb
<div class="parent-container-index">
  <div class="header-container-index"
  style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.2)),
  url(https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2574&q=80);
  height: 200px; width: 100vw;object-fit: cover;">
    <h1 class="text-center">
      All equipments
    </h1>
  </div>
</div>

<%# <h3 class="text-center mt-4">Categories: </h3> %>
<div class="categories-container justify-content-center">
  <% @categories.each do |category| %>
    <div class="category-item">
    <%= image_tag(category.image, style: "width: 40px;") %>
    <% if @category_selected === category.id %>
        <%= link_to category.name, fitness_equipments_path,
            class: (category.id === @category_selected) ? "btn btn-secondary" : "btn btn-outline-secondary"
        %>
    <% else %>
        <%= link_to category.name, fitness_equipments_path(category: category),
            class: (category.id === @category_selected) ? "btn btn-secondary" : "btn btn-outline-secondary"
        %>
    <% end %>
    </div>
  <% end %>
</div>

<div class="row justify-content-center">
  <div class="col-sm-5 mb-5">
    <%= form_with url: fitness_equipments_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Search by equipment or owner"
        %>
      <%= submit_tag "Search", name: "", class: "btn btn-secondary" %>
    <% end %>
  </div>
</div>

  <div class="container">
    <!-- Row Start -->
    <div class="row justify-content-center" style="margin:70px">
      <div class="no-equipment-found">
        <% if @equipments.count.zero? %>
          <h1>No equipment found :(</h1>
        <% end %>
      </div>

      <% @equipments.each do |equipment| %>
        <div class="col-4">
          <div class="card-fitness">
            <div class="card-img-fitness">
              <%= cl_image_tag equipment.photo.key, height: 230, width: 230, crop: :fill if equipment.photo.attached? %>
            </div>
            <div class="card-body-fitness">
              <h4 class="card-title"><strong><%= equipment.name %> </strong></h4>
              <h6><strong> Category: </strong><%= Category.find(equipment.category_id).name %></h6>
              <h6><strong> Price per day: </strong>Rs <%= equipment.price %> </h6>
              <h6><strong> Owner:  </strong><%= User.find(equipment.user_id).first_name %> </h6>
                <div id="card-button-fitness">
                <strong><%= link_to "More details", fitness_equipment_path(equipment), class:"text-decoration-none" %>
                <span>&rarr;</span></strong>
                </div>
            </div>
          </div>
        </div>
      <% end %>
    <!-- Row End -->
    </div>
  </div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag("zeus.png") %>
      Active Zeus Rental
    <% end %>
    <% if action_name == "home" %>
      <div class="form col-m-12">
        <%= form_with url: fitness_equipments_path, method: :get, class:"d-flex" do %>
          <%= text_field_tag :query,
                  params[:query],
                  class: "form-control",
                  placeholder: "Search...."
              %>
              <%= submit_tag "Search" , name: "", class: "material-symbols-outlined" %>
            <%# <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
          <% end %>
      </div>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <%= link_to "Discover equipments", fitness_equipments_path , class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
          <% if current_user.admin? %>
            <li class="nav-item active">
              <%= link_to "My listings", admin_index_path , class: "nav-link" %>
            </li>
          <% end %>
          <li class="nav-item active">
            <%= link_to "My bookings", bookings_path , class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Home", "/" , class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Edit profile", edit_user_registration_path,  class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<!-- <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">

    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag("zeus.png") %>
      Active Zeus Rental
    <% end %>

    <% if action_name == "home" %>
      <div class="form col-m-12">
        <%= form_with url: fitness_equipments_path, method: :get, class: "d-flex" do %>
          <%= text_field_tag :query,
                  params[:query],
                  class: "form-control",
                  placeholder: "Search equipment",
                  style: "border: none; font-size: 12px; padding: 8px; border-radius: 4px; background-color: #f5f5f5;"
            %>
            <%= submit_tag "Search", style: "background-color: #E67E22; color: #fff; border: none; font-size: 12px"  %>
          <% end %>
      </div>
    <% end %>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <%= link_to "Discover equipments", fitness_equipments_path , class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
          <% if current_user.admin? %>
            <li class="nav-item active">
              <%= link_to "My listings", admin_index_path , class: "nav-link" %>
            </li>
          <% end %>
          <li class="nav-item active">
            <%= link_to "My bookings", bookings_path , class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Home", "/" , class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Edit profile", edit_user_registration_path,  class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div> -->